Flores_Rubio_Luis.Web/Controllers/ConsultaController.cs
using Flores_Rubio_Luis.Domain;
using Flores_Rubio_Luis.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Flores_Rubio_Luis.Web.Controllers
{
    public class ConsultaController : Controller
    {

        IGenericService<Paciente> _pacientes;
        IGenericService<Especie> _especies;
        IGenericService<Cliente> _clientes;
        IGenericService<Consulta> _consultas;

        public ConsultaController(IGenericService<Paciente> _pacientes, IGenericService<Especie> _especies, IGenericService<Cliente> _clientes, IGenericService<Consulta> _consultas)
        {
            this._pacientes = _pacientes;
            this._especies = _especies;
            this._clientes = _clientes;
            this._consultas = _consultas;
        }

        public ActionResult GetByPacienteId(int id)
        {
            return View(_consultas.Find(x => x.PacienteId == id));
        }

        public ActionResult Create(int id)
        {
            return View(
                new Consulta
                {
                    Fecha = DateTime.Now,
                    PacienteId = id
                }
            );
        }

        [HttpPost]
        public ActionResult Create(Consulta model)
        {
            var txtRequerido = "Campo Requerido";


            if (model.Fecha > DateTime.Now)
                ViewData.ModelState.AddModelError("Fecha", "Fecha no válida");

            if (string.IsNullOrEmpty(model.Fecha.ToString()))
                ViewData.ModelState.AddModelError("Fecha", txtRequerido);


            if (string.IsNullOrEmpty(model.Motivo))
                ViewData.ModelState.AddModelError("Motivo", txtRequerido);


            if (model.Peso <= 0)
                ViewData.ModelState.AddModelError("Peso", "Inválido");


            if (!string.IsNullOrEmpty(model.Comentarios))
                if (model.Comentarios.Length > 200)
                    ViewData.ModelState.AddModelError("Comentarios", "Demasiado largo");

            if (ModelState.IsValid)
            {
                if (model.Peso > 0)
                {
                    var paciente = _pacientes.GetById(model.PacienteId);
                    paciente.Peso = model.Peso;
                    _pacientes.Edit(paciente);
                }

                _consultas.Add(model);
                return RedirectToAction("Index", "Paciente");
            }

            return View(model);
        }
    }
}

Flores_Rubio_Luis.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Flores_Rubio_Luis.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Flores_Rubio_Luis.Web/Controllers/PacienteController.cs
using Flores_Rubio_Luis.Domain;
using Flores_Rubio_Luis.Repository;
using Flores_Rubio_Luis.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Flores_Rubio_Luis.Web.Controllers
{
    public class PacienteController : Controller
    {
        IGenericService<Paciente> _servicePaciente;
        IGenericService<Cliente> _serviceCliente;
        IGenericService<Especie> _serviceEspecie;
        IGenericService<Sexo> _serviceSexo;

        public PacienteController(IGenericService<Paciente> _servicePaciente, 
            IGenericService<Cliente> _serviceCliente, 
            IGenericService<Especie> _serviceEspecie, 
            IGenericService<Sexo> _serviceSexo)
        {
            this._servicePaciente = _servicePaciente;
            this._serviceCliente = _serviceCliente;
            this._serviceEspecie = _serviceEspecie;
            this._serviceSexo = _serviceSexo;
        }


        // GET: Paciente
        public ActionResult Index()
        {
            return View(_servicePaciente.GetAll(x => x.cliente,c=>c.especie,v=>v.sexo));
        }



        public ActionResult Create()
        {
            

            ViewBag.Titulo = "Registrar";
            ViewBag.Clientes = _serviceCliente.GetAll();
            ViewBag.Especies = _serviceEspecie.GetAll();
            ViewBag.Sexos = _serviceSexo.GetAll();
            return View();
        }


        [HttpPost]
        public ActionResult Create(Paciente model)
        {
            var txtRequerido = "Campo Requerido";


             
            if (model.nro_Registro < 1)
                ViewData.ModelState.AddModelError("nro_Registro", "Mayor que 0");

            if (string.IsNullOrEmpty(model.nro_Registro.ToString()))
                ViewData.ModelState.AddModelError("nro_Registro", txtRequerido);

            if (_servicePaciente.Find(x => x.nro_Registro == model.nro_Registro).Count() > 0)
                ViewData.ModelState.AddModelError("nro_Registro", "Ya existe");


            if (model.fecha_Registro > DateTime.Now)
                ViewData.ModelState.AddModelError("fecha_Registro", "Fecha Proxima");

            if (string.IsNullOrEmpty(model.fecha_Registro.ToString()))
                ViewData.ModelState.AddModelError("fecha_Registro", txtRequerido);


            if (string.IsNullOrEmpty(model.Id_Cliente.ToString()))
                ViewData.ModelState.AddModelError("Id_Cliente", txtRequerido);


            if (string.IsNullOrEmpty(model.Nombre_Paciente))
                ViewData.ModelState.AddModelError("Nombre_Paciente", txtRequerido);


            if (string.IsNullOrEmpty(model.Id_Especie.ToString()))
                ViewData.ModelState.AddModelError("Id_Especie", txtRequerido);


            if (model.Peso <= 0)
                ViewData.ModelState.AddModelError("Peso", "Debe ser mayor que 0");


            if (!string.IsNullOrEmpty(model.Particulares) && model.Particulares.Length > 200)
                ViewData.ModelState.AddModelError("Particulares", "Demasiado largo");

            if (ModelState.IsValid)
            {
                _servicePaciente.Add(model);
                return RedirectToAction("Index");
            }

            ViewBag.Clientes = _serviceCliente.GetAll();
            ViewBag.Especies = _serviceEspecie.GetAll();
            ViewBag.Sexos = _serviceSexo.GetAll();

            return View(model);
        }

    }
}

Flores_Rubio_Luis.Web/Views/Consulta/Create.cshtml
@model Flores_Rubio_Luis.Domain.Consulta

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Consulta</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Motivo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Motivo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Motivo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Peso, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Peso, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Peso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comentarios, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comentarios, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comentarios, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PacienteId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PacienteId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PacienteId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Flores_Rubio_Luis.Web/Views/Consulta/GetByPacienteId.cshtml
@model IEnumerable<Flores_Rubio_Luis.Domain.Consulta>

@{
    ViewBag.Title = "GetByPacienteId";
}

<h2>GetByPacienteId</h2>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Fecha)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Motivo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Peso)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Comentarios)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PacienteId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Fecha)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Motivo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Peso)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Comentarios)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PacienteId)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ConsultaId }) |
            @Html.ActionLink("Details", "Details", new { id=item.ConsultaId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ConsultaId })
        </td>
    </tr>
}

</table>

Flores_Rubio_Luis.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Flores_Rubio_Luis.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Flores_Rubio_Luis.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Flores_Rubio_Luis.Web/Views/Paciente/Create.cshtml
@model Flores_Rubio_Luis.Domain.Paciente

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Paciente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nro_Registro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nro_Registro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nro_Registro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fecha_Registro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fecha_Registro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fecha_Registro, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.Label("Cliente", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.DropDownList("Id_Cliente", new SelectList(ViewBag.Clientes, "Id_Cliente", "Nombre"), "Selecciona Cliente", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Id_Cliente, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Nombre_Paciente, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre_Paciente, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre_Paciente, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Sexo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.DropDownList("Id_Sexo", new SelectList(ViewBag.Sexos, "Id_Sexo", "Nombre"), "Selecciona Sexo", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Id_Sexo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Especie", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.DropDownList("Id_Especie", new SelectList(ViewBag.Especies, "Id_Especie", "Nombre"), "Selecciona Especie", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Id_Especie, "", new { @class = "text-danger" })
            </div>
        </div>

     

        <div class="form-group">
            @Html.LabelFor(model => model.Peso, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Peso, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Peso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Particulares, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Particulares, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Particulares, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Flores_Rubio_Luis.Web/Views/Paciente/Index.cshtml
@model IEnumerable<Flores_Rubio_Luis.Domain.Paciente>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
           Nombre Cliente
        </th>
        <th>
            Especie
        </th>
        <th>
            Sexo de Paciente
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nro_Registro)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fecha_Registro)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nombre_Paciente)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Peso)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Particulares)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.cliente.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.especie.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.sexo.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nro_Registro)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.fecha_Registro)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre_Paciente)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Peso)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Particulares)
        </td>
        <td>
            @Html.ActionLink("Ver Consultas", "GetByPacienteId", "Consulta", new { id = item.Id_Paciente }, null) |
            @Html.ActionLink("Nueva Consulta", "Create", "Consulta", new { id = item.Id_Paciente }, null)
         </td>
    </tr>
}

</table>

Flores_Rubio_Luis.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Pacientes", "Index", "Paciente")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>